author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '城郊雪原'
floor: 0
tp: '回忆之蕾·拟造花萼（金）'
route:
  - idx: 1
    op: 'move'
    data: [1106, 444]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [1064, 489]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [981, 584]
  - idx: 6
    op: 'move'
    data: [937, 474]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [1012, 407]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [1019, 278]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [974, 313]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [890, 254]
  - idx: 15
    op: 'disposable'
  - idx: 16
    op: 'slow_move'
    data: [879, 252]
  - idx: 17
    op: 'disposable'
  - idx: 18
    op: 'move'
    data: [834, 296]
  - idx: 19
    op: 'move'
    data: [789, 307]
  - idx: 20
    op: 'move'
    data: [744, 326]
  - idx: 21
    op: 'patrol'
  - idx: 22
    op: 'move'
    data: [653, 314]
  - idx: 23
    op: 'move'
    data: [622, 304]
  - idx: 24
    op: 'disposable'
  - idx: 25
    op: 'move'
    data: [601, 266]
  - idx: 26
    op: 'move'
    data: [560, 221]
  - idx: 27
    op: 'disposable'
  - idx: 28
    op: 'move'
    data: [605, 223]
  - idx: 29
    op: 'move'
    data: [650, 219]
  - idx: 30
    op: 'patrol'
  - idx: 31
    op: 'move'
    data: [753, 243]
  - idx: 32
    op: 'move'
    data: [736, 208]
  - idx: 33
    op: 'move'
    data: [712, 219]
  - idx: 34
    op: 'disposable'
