author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '边缘通路'
floor: 0
tp: '以太之蕾·拟造花萼（金）'
route:
  - idx: 1
    op: 'disposable'
  - idx: 2
    op: 'move'
    data: [646, 204]
  - idx: 3
    op: 'move'
    data: [638, 183]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [655, 163]
  - idx: 6
    op: 'disposable'
