author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '铁卫禁区'
floor: 0
tp: '能源枢纽'
route:
  - idx: 1
    op: 'move'
    data: [787, 1057]
  - idx: 2
    op: 'move'
    data: [793, 955]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [804, 910]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [739, 883]
  - idx: 7
    op: 'move'
    data: [736, 919]
  - idx: 8
    op: 'move'
    data: [745, 920]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [736, 919]
  - idx: 11
    op: 'move'
    data: [733, 883]
  - idx: 12
    op: 'move'
    data: [680, 880]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [684, 839]
  - idx: 15
    op: 'move'
    data: [752, 842]
  - idx: 16
    op: 'disposable'
  - idx: 17
    op: 'move'
    data: [736, 833]
  - idx: 18
    op: 'move'
    data: [736, 721]
  - idx: 19
    op: 'move'
    data: [748, 708]
  - idx: 20
    op: 'disposable'
