author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '铁卫禁区'
floor: 0
tp: '能源枢纽'
route:
  - idx: 1
    op: 'slow_move'
    data: [733, 1105]
  - idx: 2
    op: 'slow_move'
    data: [715, 1100]
  - idx: 3
    op: 'slow_move'
    data: [728, 1078]
  - idx: 4
    op: 'disposable'
