author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
tp: '筑城领域'
route:
  - idx: 1
    op: 'disposable'
  - idx: 2
    op: 'move'
    data: [774, 406]
  - idx: 3
    op: 'move'
    data: [803, 398]
  - idx: 4
    op: 'move'
    data: [807, 310]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [801, 263]
  - idx: 7
    op: 'slow_move'
    data: [775, 261]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'slow_move'
    data: [776, 232]
  - idx: 10
    op: 'slow_move'
    data: [796, 232]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [785, 249]
  - idx: 13
    op: 'move'
    data: [665, 250]
  - idx: 14
    op: 'move'
    data: [669, 278]
  - idx: 15
    op: 'disposable'
