author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
tp: '巽风之形·凝滞虚影'
route:
  - idx: 1
    op: 'move'
    data: [599, 403]
  - idx: 2
    op: 'move'
    data: [591, 466]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [611, 466]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [631, 453]
  - idx: 7
    op: 'move'
    data: [681, 459]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [702, 412]
  - idx: 10
    op: 'move'
    data: [732, 417]
  - idx: 11
    op: 'move'
    data: [736, 446]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'slow_move'
    data: [733, 515]
  - idx: 14
    op: 'patrol'
  - idx: 15
    op: 'move'
    data: [733, 547]
  - idx: 16
    op: 'disposable'
  - idx: 17
    op: 'move'
    data: [660, 555]
  - idx: 18
    op: 'disposable'
