author: ['朗加', 'DoctorReid']
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
tp: '废弃市集'
route:
  - idx: 1
    op: 'move'
    data: [446, 375]
  - idx: 2
    op: 'move'
    data: [446, 393]
  - idx: 3
    op: 'move'
    data: [453, 399]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [426, 399]
  - idx: 6
    op: 'move'
    data: [410, 419]
  - idx: 7
    op: 'move'
    data: [411, 468]
  - idx: 8
    op: 'move'
    data: [432, 486]
  - idx: 9
    op: 'patrol'
  - idx: 10
    op: 'slow_move'
    data: [462, 509]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [471, 522]
  - idx: 13
    op: 'patrol'
  - idx: 14
    op: 'move'
    data: [487, 547]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'slow_move'
    data: [490, 554]
  - idx: 17
    op: 'move'
    data: [455, 541]
  - idx: 18
    op: 'disposable'
