author: ['朗加', 'DoctorReid']
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
tp: '积玉坊'
route:
  - idx: 1
    op: 'move'
    data: [509, 836]
  - idx: 2
    op: 'move'
    data: [506, 941]
  - idx: 3
    op: 'move'
    data: [493, 954]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [516, 948]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [516, 985]
  - idx: 8
    op: 'patrol'
  - idx: 9
    op: 'move'
    data: [508, 1007]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'slow_move'
    data: [516, 1039]
  - idx: 12
    op: 'move'
    data: [498, 1082]
  - idx: 13
    op: 'disposable'
