author: ['朗加', 'DoctorReid']
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
tp: '积玉坊'
route:
  - idx: 1
    op: 'move'
    data: [462, 789]
  - idx: 2
    op: 'move'
    data: [402, 758]
  - idx: 3
    op: 'move'
    data: [335, 752]
  - idx: 4
    op: 'move'
    data: [291, 729]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [336, 744]
  - idx: 7
    op: 'move'
    data: [409, 780]
  - idx: 8
    op: 'move'
    data: [384, 845]
  - idx: 9
    op: 'disposable'
