author: ['朗加', 'DoctorReid']
planet: '仙舟「罗浮」'
region: '廻星港'
floor: 1
tp: '野焰之径·侵蚀隧洞'
route:
  - idx: 1
    op: 'move'
    data: [482, 398]
  - idx: 2
    op: 'move'
    data: [495, 421]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [474, 315]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [521, 323]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [518, 339]
  - idx: 9
    op: 'move'
    data: [526, 339]
  - idx: 10
    op: 'move'
    data: [528, 354]
  - idx: 11
    op: 'disposable'
