author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '太卜司'
floor: 1
tp: '界寰阵'
route:
  - idx: 1
    op: 'move'
    data: [287, 331]
  - idx: 2
    op: 'move'
    data: [289, 407]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'move'
    data: [288, 455]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [315, 459]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [313, 411]
  - idx: 9
    op: 'patrol'
  - idx: 10
    op: 'move'
    data: [275, 436]
  - idx: 11
    op: 'move'
    data: [227, 436]
  - idx: 12
    op: 'move'
    data: [196, 459]
  - idx: 13
    op: 'patrol'
  - idx: 14
    op: 'slow_move'
    data: [193, 413]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'move'
    data: [186, 406]
  - idx: 17
    op: 'disposable'
  - idx: 18
    op: 'move'
    data: [228, 409]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [227, 436]
  - idx: 21
    op: 'move'
    data: [275, 436]
  - idx: 22
    op: 'move'
    data: [289, 456]
  - idx: 23
    op: 'move'
    data: [287, 540]
  - idx: 24
    op: 'move'
    data: [325, 578]
  - idx: 25
    op: 'move'
    data: [352, 578]
  - idx: 26
    op: 'disposable'
  - idx: 27
    op: 'move'
    data: [392, 621]
  - idx: 28
    op: 'move'
    data: [402, 644]
  - idx: 29
    op: 'move'
    data: [437, 685]
  - idx: 30
    op: 'move'
    data: [520, 685]
  - idx: 31
    op: 'move'
    data: [536, 703]
  - idx: 32
    op: 'patrol'
  - idx: 33
    op: 'move'
    data: [547, 701]
  - idx: 34
    op: 'disposable'
