author: ['朗加', 'DoctorReid']
planet: '仙舟「罗浮」'
region: '工造司'
floor: 0
tp: '格物院通道'
route:
  - idx: 1
    op: 'move'
    data: [391, 462]
  - idx: 2
    op: 'slow_move'
    data: [377, 486]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [354, 446]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [343, 424]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [336, 455]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [343, 424]
  - idx: 11
    op: 'slow_move'
    data: [344, 344]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [343, 335]
  - idx: 14
    op: 'move'
    data: [369, 334]
  - idx: 15
    op: 'move'
    data: [371, 415]
  - idx: 16
    op: 'move'
    data: [433, 360]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [433, 360]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [444, 343]
  - idx: 21
    op: 'patrol'
  - idx: 22
    op: 'slow_move'
    data: [389, 359]
  - idx: 23
    op: 'patrol'
  - idx: 24
    op: 'move'
    data: [405, 420]
  - idx: 25
    op: 'move'
    data: [405, 501]
  - idx: 26
    op: 'move'
    data: [382, 565]
  - idx: 27
    op: 'move'
    data: [384, 619]
  - idx: 28
    op: 'move'
    data: [420, 622]
  - idx: 29
    op: 'disposable'
  - idx: 30
    op: 'move'
    data: [358, 619]
  - idx: 31
    op: 'move'
    data: [358, 586]
  - idx: 32
    op: 'disposable'
