author: ['朗加', 'DoctorReid']
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 2
tp: '虚无之蕾·拟造花萼（赤）'
route:
  - idx: 1
    op: 'move'
    data: [633, 1157]
  - idx: 2
    op: 'move'
    data: [633, 1233, 1]
  - idx: 3
    op: 'move'
    data: [651, 1264]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [635, 1276]
  - idx: 6
    op: 'move'
    data: [624, 1289]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'slow_move'
    data: [635, 1276]
  - idx: 9
    op: 'move'
    data: [608, 1255]
  - idx: 10
    op: 'move'
    data: [614, 1125]
  - idx: 11
    op: 'move'
    data: [529, 1125]
  - idx: 12
    op: 'slow_move'
    data: [512, 1118]
  - idx: 13
    op: 'disposable'
