author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 2
tp: '虚无之蕾·拟造花萼（赤）'
route:
  - idx: 1
    op: 'move'
    data: [632, 1128]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [630, 1147]
  - idx: 4
    op: 'move'
    data: [653, 1151]
  - idx: 5
    op: 'move'
    data: [656, 1219]
  - idx: 6
    op: 'move'
    data: [690, 1215]
  - idx: 7
    op: 'move'
    data: [721, 1174]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [739, 1171]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'slow_move'
    data: [748, 1090]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [772, 1023]
  - idx: 14
    op: 'disposable'
  - idx: 15
    op: 'move'
    data: [789, 1083]
  - idx: 16
    op: 'patrol'
  - idx: 17
    op: 'slow_move'
    data: [780, 1165]
  - idx: 18
    op: 'patrol'
  - idx: 19
    op: 'move'
    data: [765, 1149]
  - idx: 20
    op: 'move'
    data: [803, 1146]
  - idx: 21
    op: 'patrol'
  - idx: 22
    op: 'move'
    data: [790, 1199]
  - idx: 23
    op: 'disposable'
