author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '鳞渊境'
floor: 0
tp: '毁灭之蕾·拟造花萼（赤）'
route:
  - idx: 1
    op: 'move'
    data: [882, 671]
  - idx: 2
    op: 'move'
    data: [843, 638]
  - idx: 3
    op: 'move'
    data: [793, 602]
  - idx: 4
    op: 'move'
    data: [726, 598]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'slow_move'
    data: [726, 577]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'slow_move'
    data: [699, 577]
  - idx: 9
    op: 'patrol'
  - idx: 10
    op: 'slow_move'
    data: [699, 598]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'slow_move'
    data: [726, 598]
  - idx: 13
    op: 'move'
    data: [699, 577]
  - idx: 14
    op: 'move'
    data: [689, 536]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'move'
    data: [710, 569]
