author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '绥园'
floor: 0
tp: '谈狐林后门'
route:
  - idx: 1
    op: 'move'
    data: [234, 444]
  - idx: 2
    op: 'move'
    data: [193, 421]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [233, 382]
  - idx: 5
    op: 'move'
    data: [233, 340]
  - idx: 6
    op: 'move'
    data: [247, 312]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [277, 326]
  - idx: 9
    op: 'move'
    data: [291, 326]
  - idx: 10
    op: 'move'
    data: [292, 359]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [300, 313]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [293, 320]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'slow_move'
    data: [366, 335]
  - idx: 17
    op: 'patrol'
