author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '幽囚狱'
floor: -3
tp: '焦热狱'
route:
  - idx: 1
    op: 'move'
    data: [1589, 1071]
  - idx: 2
    op: 'slow_move'
    data: [1617, 1073]
  - idx: 3
    op: 'interact'
    data: '按下'
  - idx: 4
    op: 'wait'
    data: ['seconds', '5']
  - idx: 5
    op: 'move'
    data: [1582, 1071]
  - idx: 6
    op: 'move'
    data: [1601, 1047]
  - idx: 7
    op: 'move'
    data: [1632, 1055]
  - idx: 8
    op: 'move'
    data: [1689, 1115]
  - idx: 9
    op: 'move'
    data: [1752, 1135]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [1653, 1161]
  - idx: 12
    op: 'disposable'
