author: ['DoctorReid']
planet: '匹诺康尼'
region: '黄金的时刻'
floor: 2
tp: '「白日梦」酒店大门'
route:
  - idx: 1
    op: 'move'
    data: [1055, 875]
  - idx: 2
    op: 'move'
    data: [1089, 783]
  - idx: 3
    op: 'disposable'
