author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '惊梦酒吧'
route:
  - idx: 1
    op: 'move'
    data: [346, 219]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [355, 208]
  - idx: 4
    op: 'move'
    data: [217, 204]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [217, 424, 2]
  - idx: 7
    op: 'move'
    data: [177, 424]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [177, 499]
  - idx: 10
    op: 'move'
    data: [211, 495]
  - idx: 11
    op: 'disposable'
