author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '冰酿之形·凝滞虚影'
route:
  - idx: 1
    op: 'move'
    data: [282, 745]
  - idx: 2
    op: 'move'
    data: [282, 764]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [282, 745]
  - idx: 5
    op: 'move'
    data: [345, 748]
  - idx: 6
    op: 'move'
    data: [345, 786]
  - idx: 7
    op: 'move'
    data: [386, 788]
  - idx: 8
    op: 'patrol'
  - idx: 9
    op: 'move'
    data: [345, 786]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'slow_move'
    data: [345, 709]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [345, 680]
  - idx: 14
    op: 'move'
    data: [409, 668]
  - idx: 15
    op: 'disposable'
