author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '藏珍之蕾·拟造花萼（金）'
route:
  - idx: 1
    op: 'move'
    data: [1331, 1395]
  - idx: 2
    op: 'move'
    data: [1335, 1331]
  - idx: 3
    op: 'move'
    data: [1345, 1329]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [1252, 1331]
  - idx: 6
    op: 'patrol'
