author: ['obtus', 'DoctorReid']
planet: '匹诺康尼'
region: '城市沙盒'
floor: 0
tp: '城市沙盒'
route:
  - idx: 1
    op: 'move'
    data: [789, 407]
  - idx: 2
    op: 'interact'
    data: '气泡弹珠机'
  - idx: 3
    op: 'wait'
    data: ['seconds', '2']
  - idx: 4
    op: 'catapult'
  - idx: 5
    op: 'wait'
    data: ['seconds', '5']
  - idx: 6
    op: 'update_pos'
    data: [669, 251]
  - idx: 7
    op: 'move'
    data: [595, 251]
  - idx: 8
    op: 'move'
    data: [558, 251]
  - idx: 9
    op: 'interact'
    data: '气泡弹珠机'
  - idx: 10
    op: 'wait'
    data: ['seconds', '2']
  - idx: 11
    op: 'catapult'
  - idx: 12
    op: 'wait'
    data: ['seconds', '5']
  - idx: 13
    op: 'update_pos'
    data: [524, 405]
  - idx: 14
    op: 'move'
    data: [517, 446]
  - idx: 15
    op: 'disposable'
  - idx: 16
    op: 'move'
    data: [518, 475]
  - idx: 17
    op: 'move'
    data: [517, 480]
  - idx: 18
    op: 'move'
    data: [506, 494]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [542, 481]
  - idx: 21
    op: 'patrol'
