author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '仓鼠球乐园'
route:
  - idx: 1
    op: 'move'
    data: [823, 380]
  - idx: 2
    op: 'move'
    data: [817, 403]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [833, 385]
  - idx: 5
    op: 'move'
    data: [810, 348]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [814, 295]
  - idx: 8
    op: 'patrol'
  - idx: 9
    op: 'move'
    data: [841, 385]
  - idx: 10
    op: 'move'
    data: [875, 379]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [900, 486]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [881, 454]
  - idx: 15
    op: 'move'
    data: [860, 385]
  - idx: 16
    op: 'move'
    data: [835, 383]
  - idx: 17
    op: 'move'
    data: [814, 275]
  - idx: 18
    op: 'move'
    data: [749, 289]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'slow_move'
    data: [720, 296]
  - idx: 21
    op: 'patrol'
  - idx: 22
    op: 'move'
    data: [672, 298]
  - idx: 23
    op: 'disposable'
  - idx: 24
    op: 'slow_move'
    data: [672, 287]
  - idx: 25
    op: 'move'
    data: [785, 264]
  - idx: 26
    op: 'patrol'
  - idx: 27
    op: 'move'
    data: [762, 247]
  - idx: 28
    op: 'patrol'
  - idx: 29
    op: 'slow_move'
    data: [724, 256]
  - idx: 30
    op: 'patrol'
  - idx: 31
    op: 'move'
    data: [701, 260]
  - idx: 32
    op: 'patrol'
