author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '哈努帮派基地'
route:
  - idx: 1
    op: 'move'
    data: [649, 1509]
  - idx: 2
    op: 'move'
    data: [635, 1530]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'slow_move'
    data: [670, 1523]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [666, 1548]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [659, 1574]
  - idx: 9
    op: 'move'
    data: [678, 1574]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'move'
    data: [639, 1585]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [649, 1607]
  - idx: 14
    op: 'disposable'
