author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '一号擂台'
floor: 0
tp: '巨星巅峰战·一号擂台'
route:
  - idx: 1
    op: 'slow_move'
    data: [791, 507]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'slow_move'
    data: [804, 485]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [763, 495]
  - idx: 6
    op: 'slow_move'
    data: [721, 494]
  - idx: 7
    op: 'disposable'
