author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '匹诺康尼大剧院'
floor: 0
tp: '调弦大厅'
route:
  - idx: 1
    op: 'move'
    data: [819, 719]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [820, 732]
  - idx: 4
    op: 'move'
    data: [867, 721]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [930, 743]
  - idx: 7
    op: 'slow_move'
    data: [935, 770]
  - idx: 8
    op: 'move'
    data: [936, 780]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [930, 743]
  - idx: 11
    op: 'move'
    data: [996, 693]
  - idx: 12
    op: 'move'
    data: [996, 644]
  - idx: 13
    op: 'patrol'
  - idx: 14
    op: 'move'
    data: [978, 660]
  - idx: 15
    op: 'disposable'
  - idx: 16
    op: 'move'
    data: [1015, 660]
  - idx: 17
    op: 'slow_move'
    data: [1026, 672]
  - idx: 18
    op: 'move'
    data: [1035, 677]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'slow_move'
    data: [1059, 630]
  - idx: 21
    op: 'move'
    data: [1069, 630]
  - idx: 22
    op: 'disposable'
  - idx: 23
    op: 'move'
    data: [1051, 554]
  - idx: 24
    op: 'move'
    data: [1063, 494]
  - idx: 25
    op: 'patrol'
  - idx: 26
    op: 'move'
    data: [1021, 487]
  - idx: 27
    op: 'patrol'
  - idx: 28
    op: 'move'
    data: [1063, 494]
  - idx: 29
    op: 'move'
    data: [1051, 437]
  - idx: 30
    op: 'disposable'
  - idx: 31
    op: 'move'
    data: [1151, 455]
  - idx: 32
    op: 'patrol'
  - idx: 33
    op: 'slow_move'
    data: [1126, 474]
  - idx: 34
    op: 'move'
    data: [1138, 484]
  - idx: 35
    op: 'disposable'
  - idx: 36
    op: 'slow_move'
    data: [1176, 430]
  - idx: 37
    op: 'move'
    data: [1188, 444]
  - idx: 38
    op: 'disposable'
  - idx: 39
    op: 'move'
    data: [1208, 386]
  - idx: 40
    op: 'patrol'
  - idx: 41
    op: 'move'
    data: [1188, 389]
  - idx: 42
    op: 'move'
    data: [1053, 384]
  - idx: 43
    op: 'disposable'
