author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '匹诺康尼大剧院'
floor: 0
tp: '福音沙龙'
route:
  - idx: 1
    op: 'move'
    data: [364, 796]
  - idx: 2
    op: 'move'
    data: [399, 770]
  - idx: 3
    op: 'move'
    data: [381, 754]
  - idx: 4
    op: 'interact'
    data: '进入梦境空间'
  - idx: 5
    op: 'wait'
    data: ['seconds', '2']
  - idx: 6
    op: 'wait'
    data: ['in_world', '20']
  - idx: 7
    op: 'wait'
    data: ['seconds', '2']
  - idx: 8
    op: 'enter_sub'
    data: ['梦境空间1', '3']
  - idx: 9
    op: 'update_pos'
    data: [987, 299]
  - idx: 10
    op: 'move'
    data: [885, 300]
  - idx: 11
    op: 'slow_move'
    data: [813, 321]
  - idx: 12
    op: 'disposable'
  - idx: 13
    op: 'move'
    data: [833, 260]
  - idx: 14
    op: 'move'
    data: [836, 236]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'patrol'
  - idx: 17
    op: 'move'
    data: [834, 222]
  - idx: 18
    op: 'move'
    data: [900, 224]
  - idx: 19
    op: 'move'
    data: [900, 282, 2]
  - idx: 20
    op: 'move'
    data: [885, 282]
  - idx: 21
    op: 'disposable'
  - idx: 22
    op: 'move'
    data: [900, 314]
  - idx: 23
    op: 'move'
    data: [899, 465, 3]
  - idx: 24
    op: 'move'
    data: [886, 489]
  - idx: 25
    op: 'patrol'
  - idx: 26
    op: 'slow_move'
    data: [886, 521]
  - idx: 27
    op: 'patrol'
  - idx: 28
    op: 'slow_move'
    data: [915, 493]
  - idx: 29
    op: 'patrol'
  - idx: 30
    op: 'move'
    data: [916, 521]
  - idx: 31
    op: 'disposable'
  - idx: 32
    op: 'move'
    data: [865, 510]
  - idx: 33
    op: 'move'
    data: [833, 507]
  - idx: 34
    op: 'disposable'
  - idx: 35
    op: 'move'
    data: [688, 504]
  - idx: 36
    op: 'disposable'
  - idx: 37
    op: 'move'
    data: [676, 377]
  - idx: 38
    op: 'disposable'
  - idx: 39
    op: 'move'
    data: [681, 307]
  - idx: 40
    op: 'move'
    data: [575, 301]
  - idx: 41
    op: 'move'
    data: [565, 286]
  - idx: 42
    op: 'move'
    data: [542, 300]
  - idx: 43
    op: 'disposable'
