author: ['朗加', 'DoctorReid']
planet: '匹诺康尼'
region: '匹诺康尼大剧院'
floor: 0
tp: '交谊厅'
route:
  - idx: 1
    op: 'move'
    data: [1211, 877]
  - idx: 2
    op: 'move'
    data: [1138, 943]
  - idx: 3
    op: 'move'
    data: [1117, 983]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'slow_move'
    data: [1089, 958]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'slow_move'
    data: [1089, 936]
  - idx: 8
    op: 'patrol'
  - idx: 9
    op: 'move'
    data: [1068, 943]
  - idx: 10
    op: 'disposable'
